name: mathdistops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.25.2  
  - cookiecutter=2.5.0
  - poetry=1.7.1
  - altair=5.2.0
  - ipykernel=6.29.0
  - scipy=1.11.4
  - pytest=7.4.4
  - pytest-cov=4.1.0
  - matplotlib=3.8.2
  - pandas=2.1.4 

